name: http_services
description: A Dart package based on Dio that provides base models to handle HTTP services requests.
version: 1.2.2
homepage: https://github.com/magicleon94/http_services

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  dio: ^3.0.9
  disposable_object: ^1.0.0
  meta: ^1.1.8

dev_dependencies:
  pedantic: ^1.8.0